name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    shell: pwsh

jobs:
  automerge:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: write

    steps:
      - uses: fastify/github-action-merge-dependabot@v3.6.2
        with:
            use-github-auto-merge: true

  build-and-test:
    name: build-and-test on ${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: | 
            6.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -p:ContinuousIntegrationBuild=True --no-restore --configuration Release
    - uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: latest
      id: setup-chrome
    - run: |
        echo Installed chromium version: ${{ steps.setup-chrome.outputs.chrome-version }}
    - name: Test
      run: dotnet test --filter FullyQualifiedName!~ExampleTests --no-build --configuration Release --verbosity normal
